# Default values for granite3.3-8b

# Resource requirements
resources:
  limits:
    nvidia.com/gpu: 1
    memory: 16Gi
    cpu: 2
  requests:
    nvidia.com/gpu: 1
    memory: 8Gi
    cpu: 2

# KEDA Autoscaling Configuration
keda:
  enabled: false
  threshold: 2
  query: 'sum(vllm:num_requests_waiting{model_name="granite-8b"})'

nodeSelector:
  nvidia.com/gpu.present: "true"

tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Equal
    value: "True"

# Model configuration
model:
  maxModelLen: 2048
  maxNumSeqs: 32
  disableLogRequests: true

# InferenceService configuration
inferenceService:
  displayName: "granite-3.3-8b"
  maxReplicas: 3
  minReplicas: 1
  modelFormat: "vLLM"
  modelName: ""
  storageUri: "oci://quay.io/redhat-ai-services/modelcar-catalog:granite-3.3-8b-instruct"
  deploymentMode: "RawDeployment"
  automountServiceAccountToken: false

# Serving Runtime configuration
servingRuntime:
  image: "registry.redhat.io/rhaiis/vllm-cuda-rhel9@sha256:094db84a1da5e8a575d0c9eade114fa30f4a2061064a338e3e032f3578f8082a"
  servedModelName: "granite-8b"
