# Default values for llama3.2-3b

# Resource requirements
resources:
  limits:
    nvidia.com/gpu: 1
    memory: 20Gi
    cpu: 4
  requests:
    nvidia.com/gpu: 1
    memory: 8Gi
    cpu: 1

# KEDA Autoscaling Configuration
keda:
  enabled: false
  threshold: 2
  query: 'sum(vllm:num_requests_waiting{model_name="llama3-2-3b"})'

nodeSelector:
  nvidia.com/gpu.present: "true"

tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Equal
    value: l40-gpu

# InferenceService configuration
inferenceService:
  displayName: "llama3.2-3b"
  maxReplicas: 3
  minReplicas: 1
  modelFormat: "vLLM"
  modelName: ""
  storageUri: "oci://quay.io/redhat-ai-services/modelcar-catalog:llama-3.2-3b-instruct"

# Serving Runtime configuration
servingRuntime:
  image: "registry.redhat.io/rhaiis/vllm-cuda-rhel9@sha256:094db84a1da5e8a575d0c9eade114fa30f4a2061064a338e3e032f3578f8082a"
  servedModelName: "llama3-2-3b"
