apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llama3-2-3b
  labels:
    {{- include "llama3-2-3b.labels" . | nindent 4 }}
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: {{ .Values.inferenceService.displayName | default "llama3.2-3b" }}
    serving.knative.openshift.io/enablePassthrough: 'true'
    {{- if .Values.keda.enabled }}
    serving.kserve.io/autoscalerClass: keda
    {{- end }}
    serving.kserve.io/deploymentMode: RawDeployment
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
  finalizers:
    - serving.kserve.io/inferenceservice-finalizer
spec:
  predictor:
    maxReplicas: {{ .Values.inferenceService.maxReplicas | default 1 }}
    minReplicas: {{ .Values.inferenceService.minReplicas | default 1 }}
    {{- if .Values.keda.enabled }}
    autoscaling:
      metrics:
        - type: External
          external:
            metric:
              backend: "prometheus"
              serverAddress: "https://thanos-querier.openshift-monitoring.svc:9092"
              query: {{ .Values.keda.metric | default "vllm:num_requests_waiting" }}
            authenticationRef:
              name: inference-prometheus-auth
            authModes: bearer
            target:
              type: Value
              value: {{ .Values.keda.threshold | default 2 }}
    {{- end }}
    model:
      modelFormat:
        name: {{ .Values.inferenceService.modelFormat | default "vLLM" }}
      name: {{ .Values.inferenceService.modelName | default "" }}
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
      runtime: llama3-2-3b
      storageUri: {{ .Values.inferenceService.storageUri | default "oci://quay.io/redhat-ai-services/modelcar-catalog:llama-3.2-3b-instruct" }}
    tolerations:
      {{- toYaml .Values.tolerations | nindent 6 }}